### ISSUE TITLE
Readme issue -> // retry up to 3 times, backing off exponentially

### ISSUE THREAD

**Issue by MrChriZ** [kentcb/Genesis.RetryWithBackoff#1]
In the read me it states it will retry up to 3 times backing off exponentially where no arguments are specified.
I can't see anything in the code which tallies with this however.
Is that just a mistake in the readme?

I'm hoping it will keep retrying indefinitely!

**Comment by kentcb** [comment]
Hi @MrChriZ , do you mean this part:

```csharp
// retry any number of times, backing off exponentially to a maximum of 3 minutes
someObservable
    .RetryWithBackoff();
```

If so, I think you've just misread the comment. It will retry indefinitely, but backing off to a maximum of 3 minutes. Let me know if that makes sense.

**Comment by MrChriZ** [comment]
Ah - sorry you're quite correct I'd misinterpretted it!
Thanks for your work on this! :)
